version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: "no"
    networks:
      - backend
    ports:
      - "8025:8025"
  kroki:
    image: yuzutech/kroki:latest
    restart: "no"
    networks:
      - backend
  #plantuml:
  #  image: plantuml/plantuml-server:jetty
  #  restart: "no"
  #  networks:
  #    - backend
  #  #ports:
  #  #  - "8001:8080"
  ruby-fcgiwrap:
    build:
      context: docker/ruby-fcgiwrap
    image: ruby-fcgiwrap:latest
    restart: "no"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./src:/home/rbe/cgi-bin:rw #,exec
      - ../:/data:rw
    networks:
      - backend
  ruby-nginx:
    build:
      context: docker/ruby-nginx
    image: ruby-nginx:latest
    depends_on:
      - ruby-fcgiwrap
    restart: "no"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ../asciiblog/content/assets:/assets:ro
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
