@startuml

autonumber
'hide footbox

box Client
actor "User" as User
participant "Browser" as Browser
participant "OTP device" as OtpDevice
participant "E-Mail Client" as EmailClient
end box
box Request Processing
participant "Dispatcher" as Dispatcher
participant "Authenticating\nFilter" as AuthFilter
participant "AccessRequest\nController" as AccessRequestController
participant "OtpController" as OtpController
end box

ref over User, OtpDevice : OTP registration process
group Request without token
    User -> Browser ++ : Opens page /resource\nwithout token
    Browser -> Dispatcher ++ : HTTP GET /resource
    Dispatcher -> AuthFilter ++ : .process()
    AuthFilter -> AuthFilter : No or invalid\ntoken received
    AuthFilter -> AccessRequestController ++ : .process()
end group
group First Factor
    AuthFilter <-- AccessRequestController -- : "Access Request"\npage
    Dispatcher <-- AuthFilter -- : "Access Request"\npage
    Browser <-- Dispatcher -- : "Access Request" page
    User <-- Browser -- : "Access Request" page
    User -> Browser ++ : Enter User ID
    note right
    * Email address is known to user and system
    * An email is sent which user needs access to
    * ATT: can be hacked or a group account
    end note
    User -> Browser : Submit form
    Browser -> Dispatcher ++ : HTTP POST /sx/access_request
    Dispatcher -> AuthFilter ++ : .filter()
    AuthFilter -> AuthFilter : Verify user\nhas access
    AuthFilter -> AuthFilter : Create token\nexchange link
    AuthFilter -> AuthFilter : Send email
    Dispatcher <-- AuthFilter -- : Result
    Browser <-- Dispatcher -- : Sucess page
    User <-- Browser -- : Success page
    ref over User, EmailClient : User checks mails
    User -> EmailClient ++ : Click token exchange link
    EmailClient -> Browser -- : Open browser: exchange link\nto sx_token
    Browser ++
    Browser -> Dispatcher ++ : HTTP GET /resource?token=...&hash=...
    Dispatcher -> AuthFilter ++ : .process()
    AuthFilter -> AuthFilter : Verify token
    AuthFilter -> AccessRequestController ++ : .process()
end group
group Second Factor
    AuthFilter <-- AccessRequestController -- : "Enter OTP" page
    Dispatcher <-- AuthFilter -- : "Enter OTP" page
    Browser <-- Dispatcher -- : "Enter OTP" page
    User <-- Browser -- : "Enter OTP" page
    note right
    Second factor
    * OTP is generated by device
    end note
    User -> OtpDevice ++ : Lookup OTP
    OtpDevice -> OtpDevice : Generate OTP
    User <-- OtpDevice -- : OTP
    User -> Browser ++ : Enter OTP
    User -> Browser : Submit form
    Browser -> Dispatcher ++ : OTP
    Dispatcher -> AuthFilter ++ : OTP
    AuthFilter -> AuthFilter : Verify OTP
    AuthFilter -> AuthFilter : Create token
    Dispatcher <-- AuthFilter -- : Token
    Browser <-- Dispatcher -- : HTTP 307 Redirect\nLocation: /resource\nSet-Cookie: ...
    Browser --
end group
ref over User, AuthFilter : Fetch resource

@enduml
