@startuml

autonumber
hide footbox

participant Browser
participant FrontDispatcher
participant ActionDispatcher
participant Controller

Browser -> FrontDispatcher ++ : HTTP GET /resource
alt HTTP method != GET, POST?
    Browser <-- FrontDispatcher : Error message
else
    alt HTTP POST?
        FrontDispatcher -> FrontDispatcher : Check CSRF token
        alt HTTP POST: CSRF token invalid?
            Browser <-- FrontDispatcher : Error message
        else
        end
    else
    end
    FrontDispatcher -> FrontDispatcher : Select\nActionDispatcher\ndepending on URL
    FrontDispatcher -> ActionDispatcher ++ : .dispatch()
    ActionDispatcher -> Controller ++ : .process()
    ActionDispatcher <-- Controller -- : Result
    FrontDispatcher <-- ActionDispatcher -- : Result
    Browser <-- FrontDispatcher -- : Result
end

@enduml
