# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'asciidoctor-kroki'
gem 'asciidoctor-plantuml'
gem 'mail'
gem 'rotp'
gem 'rqrcode'
gem 'rubocop', group: 'development'
gem 'slim'
gem 'sqlite3'
gem 'tilt'
gem 'webrick', group: 'development'
